#!/usr/bin/env sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"

cd "$ROOT_DIR"
npm run build:site >/dev/null

check_contains() {
  file_path="$1"
  pattern="$2"

  if ! grep -q -- "$pattern" "$file_path"; then
    echo "Missing expected pattern '$pattern' in $file_path" >&2
    exit 1
  fi
}

check_not_contains() {
  file_path="$1"
  pattern="$2"

  if grep -q -- "$pattern" "$file_path"; then
    echo "Unexpected pattern '$pattern' found in $file_path" >&2
    exit 1
  fi
}

check_tree_not_contains() {
  tree_path="$1"
  pattern="$2"

  if rg -Fq -- "$pattern" "$tree_path"; then
    echo "Unexpected pattern '$pattern' found under $tree_path" >&2
    exit 1
  fi
}

check_exists() {
  file_path="$1"

  if [ ! -f "$file_path" ]; then
    echo "Missing expected file $file_path" >&2
    exit 1
  fi
}

check_file_size_at_most() {
  file_path="$1"
  max_bytes="$2"
  size_bytes="$(wc -c < "$file_path" | tr -d ' ')"

  if [ "$size_bytes" -gt "$max_bytes" ]; then
    echo "Expected $file_path to be <= $max_bytes bytes but was $size_bytes bytes" >&2
    exit 1
  fi
}

check_image_has_no_opaque_white_fringe() {
  file_path="$1"
  max_pixels="$2"
  fringe_pixels="$(magick "$file_path" -crop 430x110+170+25 +repage -format '%[fx:mean*w*h]' -channel RGBA -fx '(a>0.05 && r>0.92 && g>0.92 && b>0.92)?1:0' info: | cut -d. -f1)"

  if [ "$fringe_pixels" -gt "$max_pixels" ]; then
    echo "Expected $file_path to have <= $max_pixels opaque white pixels but found $fringe_pixels" >&2
    exit 1
  fi
}

check_order() {
  file_path="$1"
  first_pattern="$2"
  second_pattern="$3"
  first_offset="$(LC_ALL=C grep -Fbo -- "$first_pattern" "$file_path" | head -n 1 | cut -d: -f1 || true)"
  second_offset="$(LC_ALL=C grep -Fbo -- "$second_pattern" "$file_path" | head -n 1 | cut -d: -f1 || true)"

  if [ -z "$first_offset" ] || [ -z "$second_offset" ]; then
    echo "Missing expected ordered patterns '$first_pattern' or '$second_pattern' in $file_path" >&2
    exit 1
  fi

  if [ "$first_offset" -ge "$second_offset" ]; then
    echo "Expected '$first_pattern' to appear before '$second_pattern' in $file_path" >&2
    exit 1
  fi
}

check_exists scripts/generate-index-page.mjs
check_exists scripts/generate-legal-pages.mjs
check_exists scripts/shared/landing-shell.mjs
check_exists src/images/figure-002.webp
check_exists src/images/figure-003-trimmed.webp
check_exists src/images/figure-004.webp
check_exists src/images/figure-004-oil-cuts-transparent.webp
check_exists src/images/figure-005-upstream-phases-transparent.webp
check_exists src/images/figure-006-block-assignment-transparent.webp
check_exists src/images/figure-006.webp
check_exists src/images/figure-007.webp
check_exists src/images/figure-008.webp
check_exists src/images/figure-009.webp
check_exists src/images/figure-011.webp
check_exists src/images/figure-012.webp
check_exists src/images/figure-013.webp
check_exists src/images/figure-014.webp
check_exists src/images/figure-015.webp
check_exists src/images/figure-016.webp
check_exists src/images/figure-019.webp
check_exists src/images/figure-020.webp
check_exists src/images/figure-021.webp
check_exists src/images/figure-001.webp
check_exists src/images/figure-003-trimmed.png
check_exists assets/images/west-africa-intelligence-overlay.svg
check_exists assets/images/upstream-atlas-nav-logo.webp
check_exists assets/icons/homepage/icon-research.svg
check_exists assets/icons/homepage/icon-industry-monitoring.svg
check_exists assets/icons/homepage/icon-intelligence.svg
check_exists assets/icons/homepage/icon-start-reading.svg
check_exists assets/icons/homepage/icon-menu.svg
check_exists assets/icons/homepage/icon-close.svg
check_exists assets/icons/homepage/icon-production.svg
check_exists assets/icons/homepage/icon-exploration.svg
check_exists assets/icons/homepage/icon-fiscal.svg
check_exists assets/icons/homepage/icon-regulation.svg
check_exists assets/icons/homepage-cropped/icon-research.png
check_exists assets/icons/homepage-cropped/icon-industry-monitoring.png
check_exists assets/icons/homepage-cropped/icon-intelligence.png
check_exists assets/icons/homepage-cropped/icon-production.png
check_exists assets/icons/homepage-cropped/icon-exploration.png
check_exists assets/icons/homepage-cropped/icon-fiscal.png
check_exists assets/icons/homepage-cropped/icon-regulation.png
check_exists assets/icons/homepage-cropped/icon-audience-research.png
check_exists assets/icons/homepage-cropped/icon-audience-policy.png
check_exists assets/icons/homepage-cropped/icon-audience-operators.png
check_exists assets/icons/homepage/icon-audience-research.svg
check_exists assets/icons/homepage/icon-audience-policy.svg
check_exists assets/icons/homepage/icon-audience-operators.svg
check_exists assets/icons/homepage-sprite.svg
check_contains package.json '"build:index": "node scripts/generate-index-page.mjs"'
check_contains package.json '"build:legal": "node scripts/generate-legal-pages.mjs"'
check_contains package.json '"build:site": "rm -rf public && mkdir -p public && npm run build:index && npm run build:legal && npm run build:chapters'
check_contains .github/workflows/pages.yml 'run: npm run build:site'
check_not_contains .github/workflows/pages.yml 'cp index.html public/index.html'
check_contains scripts/generate-index-page.mjs 'renderLandingHead'
check_contains scripts/generate-index-page.mjs 'renderLandingHeader'
check_contains scripts/generate-index-page.mjs 'renderLandingFooter'
check_contains scripts/generate-chapters-page.mjs 'from "./shared/landing-shell.mjs"'
check_contains scripts/generate-chapters-page.mjs 'renderLandingHead'
check_contains scripts/generate-chapters-page.mjs 'renderLandingHeader'
check_contains scripts/generate-chapters-page.mjs 'renderLandingFooter'
check_contains scripts/shared/landing-shell.mjs 'function renderLandingHead'
check_contains scripts/shared/landing-shell.mjs 'function renderLandingHeader'
check_contains scripts/shared/landing-shell.mjs 'function renderLandingFooter'
check_not_contains book.toml 'git-repository-url = "https://github.com/peakwalk/west-africa-petroleum-book"'
check_not_contains book.toml 'edit-url-template = "https://github.com/peakwalk/west-africa-petroleum-book/edit/main/{path}"'

check_contains public/index.html 'class="landing-shell"'
check_contains public/index.html 'class="hero-panel"'
check_contains public/index.html 'class="chapter-preview-card"'
check_contains public/index.html 'class="site-header-inner"'
check_contains public/index.html 'upstream-atlas-favicon.png?v=2'
check_contains public/index.html 'upstream-atlas-nav-logo.webp'
check_not_contains public/index.html 'upstream-atlas-nav-logo.png'
check_contains public/index.html 'upstream-atlas-icon.png'
check_contains public/index.html 'href="chapters/"'
check_contains public/index.html 'class="current-link" href="/">Home</a>'
check_contains public/index.html 'href="#countries">Countries</a>'
check_contains public/index.html 'href="#about">About</a>'
check_contains public/index.html 'href="#resources">Resources</a>'
check_order public/index.html 'href="#about">About</a>' 'href="#resources">Resources</a>'
check_contains public/index.html 'class="header-contact-link"'
check_contains public/index.html 'mailto:matt@operatorassetexchange.com?subject=Upstream%20Atlas'
check_contains public/index.html 'aria-label="Contact Us"'
check_not_contains public/index.html 'class="nav-search"'
check_not_contains public/index.html 'href="book/toc.html"'
check_not_contains public/index.html 'section-heading section-heading-centered'
check_contains public/index.html 'West African Petroleum Intelligence'
check_contains public/index.html 'West African upstream intelligence built on a rigorous reference base.'
check_contains public/index.html 'rigorous upstream reference base'
check_contains public/index.html 'Reference book'
check_contains public/index.html 'Available now'
check_contains public/index.html 'In build'
check_contains public/index.html 'Platform Intelligence'
check_contains public/index.html 'Coming Soon'
check_contains public/index.html 'class="feature-card-icon ua-icon-image ua-icon-image--feature"'
check_contains public/index.html 'assets/icons/homepage-cropped/icon-research.png'
check_contains public/index.html 'assets/icons/homepage-cropped/icon-industry-monitoring.png'
check_contains public/index.html 'assets/icons/homepage-cropped/icon-intelligence.png'
check_contains public/index.html 'assets/icons/homepage-sprite.svg#icon-start-reading'
check_contains public/index.html 'assets/icons/homepage-sprite.svg#icon-menu'
check_contains public/index.html 'assets/icons/homepage-sprite.svg#icon-close'
check_contains public/index.html 'assets/icons/homepage-cropped/icon-production.png'
check_contains public/index.html 'assets/icons/homepage-cropped/icon-exploration.png'
check_contains public/index.html 'assets/icons/homepage-cropped/icon-fiscal.png'
check_contains public/index.html 'assets/icons/homepage-cropped/icon-regulation.png'
check_contains public/index.html 'assets/icons/homepage-cropped/icon-audience-research.png'
check_contains public/index.html 'assets/icons/homepage-cropped/icon-audience-policy.png'
check_contains public/index.html 'assets/icons/homepage-cropped/icon-audience-operators.png'
check_not_contains public/index.html 'assets/icons/homepage-cropped/icon-start-reading.png'
check_not_contains public/index.html 'assets/icons/homepage-cropped/icon-menu.png'
check_not_contains public/index.html 'assets/icons/homepage-cropped/icon-close.png'
check_contains public/index.html 'class="button-icon ua-icon ua-icon--sm"'
check_contains public/index.html 'class="mobile-nav-icon mobile-nav-icon-menu ua-icon ua-icon--sm"'
check_contains public/index.html 'class="mobile-nav-icon mobile-nav-icon-close ua-icon ua-icon--sm"'
check_not_contains public/index.html 'class="mobile-nav-contact"'
check_not_contains public/index.html '>Contact Us</a>'
check_contains public/index.html 'class="reference-evidence-grid"'
check_contains public/index.html 'Country reserves'
check_contains public/index.html 'Country Intelligence'
check_contains public/index.html 'class="country-card country-card-compact"'
check_contains public/index.html 'Additional markets'
check_contains public/index.html 'class="country-card-top"'
check_contains public/index.html 'class="country-card-badge"'
check_contains public/index.html 'class="country-signal-grid"'
check_contains public/index.html 'class="country-signal-icon ua-icon-image ua-icon-image--signal"'
check_contains public/index.html 'class="country-signal-copy"'
check_contains public/index.html 'class="country-signal-value"'
check_contains public/index.html 'Template ready'
check_contains public/index.html 'Brief queued'
check_contains public/index.html 'Signals planned'
check_contains public/index.html 'class="chapters-link-row"'
check_contains public/index.html 'class="site-footer site-footer-detailed"'
check_contains public/index.html 'class="brand-mark-image brand-mark-image-full"'
check_contains public/index.html 'class="brand-mark-image brand-mark-image-compact"'
check_contains public/index.html 'Terms of Use'
check_contains public/index.html 'Privacy Policy'
check_contains public/index.html 'Cookie Policy'
check_not_contains public/index.html 'class="footer-brand-lockup"'
check_not_contains public/index.html 'footer-brand-surface'
check_not_contains public/index.html 'upstream-atlas-wordmark.png'
check_not_contains public/index.html 'upstream-atlas-logo.png'
check_contains public/index.html 'fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap'
check_exists public/assets/icons/homepage/icon-research.svg
check_exists public/assets/icons/homepage/icon-industry-monitoring.svg
check_exists public/assets/icons/homepage/icon-intelligence.svg
check_exists public/assets/icons/homepage/icon-start-reading.svg
check_exists public/assets/icons/homepage/icon-menu.svg
check_exists public/assets/icons/homepage/icon-close.svg
check_exists public/assets/icons/homepage/icon-production.svg
check_exists public/assets/icons/homepage/icon-exploration.svg
check_exists public/assets/icons/homepage/icon-fiscal.svg
check_exists public/assets/icons/homepage/icon-regulation.svg
check_exists public/assets/icons/homepage-cropped/icon-research.png
check_exists public/assets/icons/homepage-cropped/icon-industry-monitoring.png
check_exists public/assets/icons/homepage-cropped/icon-intelligence.png
check_exists public/assets/icons/homepage-cropped/icon-production.png
check_exists public/assets/icons/homepage-cropped/icon-exploration.png
check_exists public/assets/icons/homepage-cropped/icon-fiscal.png
check_exists public/assets/icons/homepage-cropped/icon-regulation.png
check_exists public/assets/icons/homepage-cropped/icon-audience-research.png
check_exists public/assets/icons/homepage-cropped/icon-audience-policy.png
check_exists public/assets/icons/homepage-cropped/icon-audience-operators.png
check_exists public/assets/icons/homepage/icon-audience-research.svg
check_exists public/assets/icons/homepage/icon-audience-policy.svg
check_exists public/assets/icons/homepage/icon-audience-operators.svg
check_exists public/assets/icons/homepage-sprite.svg
check_exists public/assets/images/upstream-atlas-nav-logo.webp
check_file_size_at_most public/assets/images/upstream-atlas-icon.png 50000
check_file_size_at_most public/assets/images/upstream-atlas-wordmark.png 110000
check_file_size_at_most public/assets/images/upstream-atlas-nav-logo.webp 80000
check_image_has_no_opaque_white_fringe public/assets/images/upstream-atlas-nav-logo.webp 50
check_file_size_at_most public/assets/images/prototype-hero.jpg 120000
check_contains assets/css/landing.css '--page-bg: #f7f8f9;'
check_contains assets/css/landing.css '--surface-muted: #eef2f4;'
check_contains assets/css/landing.css '--ink-primary: #0b1f33;'
check_contains assets/css/landing.css '--brand-blue: #3163c2;'
check_contains assets/css/landing.css '--brand-blue-deep: #264d97;'
check_contains assets/css/landing.css '--footer-bg: #0b1f33;'
check_contains assets/css/landing.css '--secondary: #d88a1d;'
check_contains assets/css/landing.css '--text: var(--ink-primary);'
check_contains assets/css/landing.css 'opacity: 0.28;'
check_contains assets/css/landing.css 'background: linear-gradient(135deg, rgba(38, 77, 151, 0.82) 0%, rgba(11, 31, 51, 0.84) 100%);'
check_contains assets/css/landing.css 'background: var(--brand-blue-deep);'
check_contains assets/css/landing.css 'background: url("../images/prototype-hero.jpg") center right / cover;'
check_contains assets/css/landing.css 'background: url("../images/west-africa-intelligence-overlay.svg") center / cover no-repeat;'
check_contains assets/css/landing.css 'opacity: 0.09;'
check_not_contains assets/css/landing.css '--primary: #264d97;'
check_contains assets/css/landing.css '@media (min-width: 901px) {'
check_contains assets/css/landing.css '.hero-signal-panel {'
check_contains assets/css/landing.css 'margin-top: clamp(17rem, 30vw, 20.5rem);'
check_contains assets/css/landing.css '.chapters-link-row {'
check_contains assets/css/landing.css 'width: min(76rem, calc(100% - 2rem));'
check_contains assets/css/landing.css '.chapters-link {'
check_contains assets/css/landing.css 'margin: 0;'
check_contains assets/css/landing.css 'border-radius: 0.5rem;'
check_contains assets/css/landing.css 'font-weight: 500;'
check_contains assets/css/landing.css '.brand-mark-image {'
check_contains assets/css/landing.css '.brand-mark-image-compact {'
check_not_contains assets/css/landing.css '.footer-brand-surface {'
check_contains assets/css/landing.css 'font-family: "Manrope", "Inter", sans-serif;'
check_contains assets/css/landing.css '.mobile-nav-toggle {'
check_contains assets/css/landing.css '.mobile-nav-toggle .mobile-nav-icon-close {'
check_contains assets/css/landing.css '.header-actions {'
check_contains assets/css/landing.css '.header-contact-link::after {'
check_contains assets/css/landing.css '.mobile-nav-contact {'
check_contains assets/css/landing.css '.ua-icon {'
check_contains assets/css/landing.css '.ua-icon-image {'
check_contains assets/css/landing.css '.ua-icon--feature {'
check_contains assets/css/landing.css '.ua-icon-image--feature {'
check_contains assets/css/landing.css '.ua-icon-image--signal {'
check_contains assets/css/landing.css '.feature-card-icon {'
check_contains assets/css/landing.css '.button-icon {'
check_contains assets/css/landing.css '.mobile-nav-icon-close {'
check_contains assets/css/landing.css '.mobile-nav-menu\[open\] .mobile-nav-toggle .mobile-nav-icon-close {'
check_contains assets/css/landing.css '.country-signal-icon {'
check_contains assets/css/landing.css '.country-signal-copy {'
check_contains assets/css/landing.css '.ua-icon--audience {'
check_contains assets/css/landing.css '@media (max-width: 700px) {'
check_contains assets/css/landing.css '.site-header-inner {'
check_contains assets/css/landing.css 'grid-template-columns: auto auto;'
check_contains assets/css/landing.css '@media (max-width: 360px) {'
check_contains assets/css/landing.css '.brand-mark-image-full {'
check_contains assets/css/landing.css '.mobile-nav-toggle .button-label {'
check_not_contains assets/css/landing.css '@import url("https://fonts.googleapis.com'
check_not_contains scripts/generate-chapters-page.mjs 'replaceAll('
check_not_contains assets/css/chapters.css 'var(--primary)'
check_not_contains assets/css/chapters.css '--primary:'
check_contains assets/css/chapters.css 'var(--ink-primary)'
check_contains assets/css/chapters.css 'var(--brand-blue)'

check_exists public/chapters/index.html
check_contains public/chapters/index.html 'Chapter Library'
check_contains public/chapters/index.html 'class="site-header-inner"'
check_contains public/chapters/index.html 'upstream-atlas-nav-logo.webp'
check_not_contains public/chapters/index.html 'upstream-atlas-nav-logo.png'
check_contains public/chapters/index.html 'upstream-atlas-icon.png'
check_contains public/chapters/index.html 'class="button button-header" href="../book/">'
check_contains public/chapters/index.html '<span class="button-label">Start Reading</span>'
check_contains public/chapters/index.html '../assets/icons/homepage-sprite.svg#icon-start-reading'
check_not_contains public/chapters/index.html '../assets/icons/homepage-cropped/icon-start-reading.png'
check_not_contains public/chapters/index.html '../assets/icons/homepage-cropped/icon-menu.png'
check_not_contains public/chapters/index.html '../assets/icons/homepage-cropped/icon-close.png'
check_contains public/chapters/index.html 'class="current-link" href="./">Chapters</a>'
check_contains public/chapters/index.html 'href="../#countries">Countries</a>'
check_contains public/chapters/index.html 'href="../#about">About</a>'
check_contains public/chapters/index.html 'href="../#resources">Resources</a>'
check_order public/chapters/index.html 'href="../#about">About</a>' 'href="../#resources">Resources</a>'
check_contains public/chapters/index.html 'class="header-contact-link"'
check_contains public/chapters/index.html 'mailto:matt@operatorassetexchange.com?subject=Upstream%20Atlas'
check_not_contains public/chapters/index.html 'class="mobile-nav-contact"'
check_not_contains public/chapters/index.html '>Contact Us</a>'
check_not_contains public/index.html '<path d="M5 4.75A1.75 1.75 0 0 1 6.75 3h8.5A1.75 1.75 0 0 1 17 4.75v14.5A1.75 1.75 0 0 1 15.25 21h-8.5A1.75 1.75 0 0 1 5 19.25Z'
check_contains public/chapters/index.html 'class="site-footer site-footer-detailed"'
check_contains public/chapters/index.html 'Terms of Use'
check_contains public/chapters/index.html 'Privacy Policy'
check_contains public/chapters/index.html 'Cookie Policy'
check_contains public/chapters/index.html 'fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap'
check_not_contains public/chapters/index.html 'class="nav-search"'
check_not_contains public/chapters/index.html 'href="../#audience"'
check_not_contains public/chapters/index.html 'class="footer-brand-lockup"'
check_not_contains public/chapters/index.html 'footer-brand-surface'
check_not_contains public/chapters/index.html 'upstream-atlas-wordmark.png'
check_not_contains public/chapters/index.html 'upstream-atlas-logo.png'
check_contains public/chapters/index.html '<h2>Part I: General Information on the Oil Industry</h2>'
check_contains public/chapters/index.html 'class="chapter-card-header"'
check_contains public/chapters/index.html 'class="chapter-card-status"'
check_contains public/chapters/index.html 'class="chapter-card-reading"'
check_contains public/chapters/index.html 'data-tooltip="Estimated reading time based on'
check_contains public/chapters/index.html 'Estimated reading time based on'
check_contains public/chapters/index.html 'Estimated reading time based on about 64 words and a front-matter overview pace.'
check_contains public/chapters/index.html 'Additional Resources'
check_not_contains public/chapters/index.html 'Open chapter'
check_not_contains public/chapters/index.html ' entries</p>'
check_not_contains public/chapters/index.html 'title="Estimated reading time based on'
check_contains public/chapters/index.html 'General Information on the Oil Industry'
check_contains public/chapters/index.html '../book/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.html'

check_exists public/terms-of-use.html
check_exists public/privacy-policy.html
check_exists public/cookie-policy.html
check_contains public/terms-of-use.html 'class="legal-page"'
check_contains public/privacy-policy.html 'class="legal-page"'
check_contains public/cookie-policy.html 'class="legal-page"'
check_contains public/terms-of-use.html 'Document pending final approved text'
check_contains public/privacy-policy.html 'Document pending final approved text'
check_contains public/cookie-policy.html 'Document pending final approved text'
check_contains public/terms-of-use.html 'Status: Final approved text pending publication'
check_contains public/privacy-policy.html 'Status: Final approved text pending publication'
check_contains public/cookie-policy.html 'Status: Final approved text pending publication'
check_contains public/terms-of-use.html 'href="privacy-policy.html"'
check_contains public/privacy-policy.html 'href="cookie-policy.html"'
check_contains public/cookie-policy.html 'href="terms-of-use.html"'
check_contains public/terms-of-use.html 'href="index.html"'
check_contains public/terms-of-use.html 'upstream-atlas-nav-logo.webp'
check_contains public/privacy-policy.html 'upstream-atlas-nav-logo.webp'
check_contains public/cookie-policy.html 'upstream-atlas-nav-logo.webp'
check_not_contains public/terms-of-use.html 'upstream-atlas-nav-logo.png'
check_not_contains public/privacy-policy.html 'upstream-atlas-nav-logo.png'
check_not_contains public/cookie-policy.html 'upstream-atlas-nav-logo.png'
check_not_contains public/terms-of-use.html 'legal-page-brand-copy'
check_not_contains public/privacy-policy.html 'legal-page-brand-copy'
check_not_contains public/cookie-policy.html 'legal-page-brand-copy'
check_not_contains public/terms-of-use.html 'href="/"'
check_order public/terms-of-use.html '<a href="index.html#about">About</a>' '<p class="site-footer-heading">Resources</p>'

check_contains public/book/index.html 'id="mdbook-sidebar"'
check_contains public/book/index.html 'class="light sidebar-visible"'
check_contains public/book/index.html 'id="book-progress-fill"'
check_contains public/book/index.html 'class="book-toolbar"'
check_contains public/book/index.html 'class="toolbar-left"'
check_contains public/book/index.html 'class="toolbar-right"'
check_contains public/book/index.html 'class="icon-button toolbar-link toolbar-contact-link"'
check_contains public/book/index.html 'href="mailto:matt@operatorassetexchange.com?subject=Upstream%20Atlas"'
check_contains public/book/index.html 'upstream-atlas-nav-logo.webp'
check_not_contains public/book/index.html 'upstream-atlas-nav-logo.png'
check_contains public/book/index.html 'upstream-atlas-icon.png'
check_contains public/book/index.html 'class="book-home-icon book-home-icon-full"'
check_contains public/book/index.html 'class="book-home-icon book-home-icon-compact"'
check_contains public/book/index.html 'title="Contact Us"'
check_not_contains public/book/index.html 'title="Git repository"'
check_contains public/book/index.html 'class="toolbar-search-slot hidden"'
check_contains public/book/index.html 'id="mdbook-search-wrapper" class="hidden"'
check_contains public/book/index.html 'id="mdbook-content" class="content reader-layout"'
check_contains public/book/index.html 'reader-layout'
check_contains public/book/index.html 'reader-main'
check_contains public/book/index.html 'reader-outline'
check_contains public/book/index.html 'id="mdbook-reader-scroll"'
check_contains public/book/index.html 'id="mdbook-outline-scroll"'
check_contains public/book/index.html 'class="reader-main-inner"'
check_contains public/book/index.html 'reader-article'
check_contains public/book/index.html 'book-sidebar-shell'
check_not_contains public/book/index.html 'sidebar-resize-indicator'
check_not_contains public/book/index.html 'class="sidebar-resize-handle"'
check_not_contains public/book/index.html 'title="Print this book"'
check_not_contains public/book/index.html 'title="Suggest an edit"'
check_not_contains public/book/index.html 'title="Change theme"'
check_contains public/book/index.html 'class="book-outline-inner"'
check_contains public/book/index.html 'class="chapter-nav-card chapter-nav-next"'
check_not_contains public/book/toc.html 'href="index.html" target="_parent">Home</a>'
check_not_contains public/book/print.html 'title="Git repository"'
check_not_contains public/book/404.html 'title="Git repository"'
check_tree_not_contains public/book 'https://github.com/peakwalk/west-africa-petroleum-book'
check_contains public/book/chapters/chapter-04-comparative-study-of-tax-regimes-in-selected-west-african-countries.html 'reader-layout'
check_contains public/book/chapters/chapter-04-comparative-study-of-tax-regimes-in-selected-west-african-countries.html 'reader-main'
check_contains public/book/chapters/chapter-04-comparative-study-of-tax-regimes-in-selected-west-african-countries.html 'reader-outline'
check_contains public/book/chapters/chapter-04-comparative-study-of-tax-regimes-in-selected-west-african-countries.html 'reader-article'
check_not_contains public/book/chapters/bibliographical-references.html 'TABLE OF CONTENTS'
check_contains src/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.md 'figure-002.webp'
check_contains src/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.md 'figure-003-trimmed.webp'
check_contains src/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.md 'figure-004.webp'
check_contains src/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.md 'figure-004-oil-cuts-transparent.webp'
check_contains src/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.md 'figure-005.jpg'
check_not_contains src/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.md 'figure-002.png'
check_not_contains src/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.md 'figure-003-trimmed.png'
check_not_contains src/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.md 'figure-004.png'
check_not_contains src/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.md '0 to 80-100°C'
check_not_contains src/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.md '120 to 180°C'
check_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-005-upstream-phases-transparent.webp'
check_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-006-block-assignment-transparent.webp'
check_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-006.webp'
check_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-007.webp'
check_order src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-007.webp' 'figure-006.webp'
check_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-008.webp'
check_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-010.jpg'
check_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-011.webp'
check_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-012.webp'
check_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-013.webp'
check_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-014.webp'
check_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-015.webp'
check_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-016.webp'
check_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-017.jpg'
check_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-018.jpg'
check_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-019.webp'
check_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-020.webp'
check_not_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-006.png'
check_not_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-007.png'
check_not_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-008.png'
check_not_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-009.png'
check_not_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-011.png'
check_not_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-012.png'
check_not_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-013.png'
check_not_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-014.png'
check_not_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-015.png'
check_not_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-016.png'
check_not_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-019.png'
check_not_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'figure-020.png'
check_not_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'Multiple qv streamers'
check_not_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md '![Figure 009](../images/figure-009.webp)'
check_not_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'Authorization to operate'
check_not_contains src/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.md 'Exploration Authorization'
check_contains src/chapters/chapter-03-tax-regimes-in-the-petroleum-sector.md 'figure-021.webp'
check_not_contains src/chapters/chapter-03-tax-regimes-in-the-petroleum-sector.md 'figure-021.png'
check_contains src/SUMMARY.md 'chapters/cover.md'
check_contains src/chapters/cover.md 'figure-001.webp'
check_not_contains src/chapters/cover.md 'figure-001.png'
check_contains public/book/chapters/cover.html 'class="book-cover"'
check_contains public/book/chapters/cover.html 'class="book-cover-frame"'
check_contains public/book/chapters/cover.html 'class="book-cover-kicker"'
check_contains public/book/chapters/cover.html 'class="book-cover-title"'
check_contains public/book/chapters/cover.html 'class="book-cover-subtitle"'
check_contains public/book/chapters/cover.html 'class="book-cover-figure"'
check_contains public/book/chapters/cover.html 'class="book-cover-footer"'
check_contains public/book/chapters/cover.html 'class="book-cover-imprint"'
check_contains public/book/chapters/cover.html 'class="book-cover-entry"'
check_contains public/book/chapters/cover.html 'class="book-cover-entry-link"'
check_contains public/book/chapters/cover.html 'Start reading'
check_contains public/book/chapters/cover.html 'href="../chapters/foreword.html"'
check_contains public/book/chapters/cover.html 'figure-001.webp'
check_not_contains public/book/chapters/cover.html 'figure-001.png'
check_contains public/book/chapters/cover.html 'function applyInitialBookPageVariant()'
check_contains public/book/chapters/cover.html 'document.body.classList.add("book-page-cover")'
check_order public/book/chapters/cover.html 'document.body.classList.add("book-page-cover")' 'id="mdbook-content" class="content reader-layout"'
check_contains public/book/chapters/front-matter.html 'http-equiv="refresh"'
check_contains public/book/chapters/front-matter.html 'url=cover.html'
check_contains public/book/chapters/front-matter.html 'window.location.replace(target)'
check_contains public/book/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.html 'figure-002.webp'
check_contains public/book/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.html 'figure-003-trimmed.webp'
check_contains public/book/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.html 'figure-004.webp'
check_contains public/book/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.html 'figure-004-oil-cuts-transparent.webp'
check_contains public/book/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.html '30.031<sup>1</sup>'
check_contains public/book/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.html '<p><sup>1</sup> Data Ministries</p>'
check_contains public/book/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.html '<p><sup>2</sup> RPS Energy Report, 2006</p>'
check_not_contains public/book/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.html 'figure-002.png'
check_not_contains public/book/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.html 'figure-003-trimmed.png'
check_not_contains public/book/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.html 'figure-004.png'
check_not_contains public/book/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.html '<p>0 to 80-100°C</p>'
check_not_contains public/book/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.html '<p>120 to 180°C</p>'
check_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-005-upstream-phases-transparent.webp'
check_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-006-block-assignment-transparent.webp'
check_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-006.webp'
check_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-007.webp'
check_order public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-007.webp' 'figure-006.webp'
check_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-008.webp'
check_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-011.webp'
check_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-012.webp'
check_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-013.webp'
check_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-014.webp'
check_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-015.webp'
check_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-016.webp'
check_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-019.webp'
check_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-020.webp'
check_not_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html '<p>Authorization to operate</p>'
check_not_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html '<p>Exploration Authorization</p>'
check_not_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-006.png'
check_not_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-007.png'
check_not_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-008.png'
check_not_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-009.png'
check_not_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-011.png'
check_not_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-012.png'
check_not_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-013.png'
check_not_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-014.png'
check_not_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-015.png'
check_not_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-016.png'
check_not_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-019.png'
check_not_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-020.png'
check_not_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html '<p>Multiple qv streamers</p>'
check_not_contains public/book/chapters/chapter-02-different-phases-of-upstream-oil-and-the-roles-of-states.html 'figure-009.webp'
check_contains public/book/chapters/chapter-03-tax-regimes-in-the-petroleum-sector.html 'figure-021.webp'
check_not_contains public/book/chapters/chapter-03-tax-regimes-in-the-petroleum-sector.html 'figure-021.png'
check_contains public/book/chapters/cover.html 'Exploration and Exploitation of Petroleum Resources in West Africa'
check_contains public/book/chapters/cover.html 'Roles and responsibilities of States and analysis of tax regimes'
check_contains public/book/chapters/cover.html 'Upstream Atlas Reference Edition'
check_contains public/book/chapters/cover.html 'Digital Reading Edition'
check_file_size_at_most public/book/images/figure-017.jpg 200000
check_file_size_at_most public/book/images/figure-018.jpg 200000
check_contains public/book/chapters/list-of-figures.html 'List of Figures'
check_contains public/book/chapters/list-of-figures.html 'class="reference-index reference-index-figures"'
check_contains public/book/chapters/list-of-figures.html 'class="chapter-nav-card chapter-nav-next"'
check_contains public/book/chapters/list-of-figures.html 'chapter-01-value-chain-of-the-hydrocarbon-sector.html#figure-1'
check_contains public/book/chapters/list-of-figures.html 'chapter-04-comparative-study-of-tax-regimes-in-selected-west-african-countries.html#figure-32'
check_contains public/book/chapters/list-of-tables.html 'List of Tables'
check_contains public/book/chapters/list-of-tables.html 'class="reference-index reference-index-tables"'
check_contains public/book/chapters/list-of-tables.html 'class="chapter-nav-card chapter-nav-previous"'
check_contains public/book/chapters/list-of-tables.html 'class="chapter-nav-card chapter-nav-next"'
check_contains public/book/chapters/list-of-tables.html 'chapter-01-value-chain-of-the-hydrocarbon-sector.html#table-1'
check_contains public/book/chapters/list-of-tables.html 'chapter-04-comparative-study-of-tax-regimes-in-selected-west-african-countries.html#table-11'
check_contains public/book/chapters/abbreviations-acronyms-and-abbreviations.html 'Abbreviations, Acronyms and Abbreviations'
check_contains public/book/chapters/abbreviations-acronyms-and-abbreviations.html 'class="reference-index reference-index-abbreviations"'
check_contains public/book/chapters/abbreviations-acronyms-and-abbreviations.html 'class="chapter-nav-card chapter-nav-previous"'
check_contains public/book/chapters/abbreviations-acronyms-and-abbreviations.html 'class="chapter-nav-card chapter-nav-next"'
check_contains public/book/chapters/abbreviations-acronyms-and-abbreviations.html 'class="reference-glossary-list"'
check_contains public/book/chapters/abbreviations-acronyms-and-abbreviations.html 'ABEX'
check_contains public/book/chapters/abbreviations-acronyms-and-abbreviations.html 'AfCFTA'
check_contains public/book/chapters/glossary.html 'class="api-density-formula"'
node -e 'const fs=require("fs");const html=fs.readFileSync("public/book/chapters/glossary.html","utf8");if(!/API\s*density\s*=/.test(html)||!/Density\s*at\s*15°C/.test(html)||!html.includes("141.5")||!html.includes("131.5")||html.includes("Densité")||html.includes("141,5")||html.includes("131,5")){console.error("Expected glossary formula to use English density terms and decimal points");process.exit(1);}'
check_not_contains public/book/chapters/glossary.html 'language-math'
check_order public/book/chapters/glossary.html 'It is calculated by the formula:' 'class="api-density-formula"'
check_order public/book/chapters/glossary.html 'class="api-density-formula"' 'Light oil (API &gt; 30°)'
check_contains public/book/toc.html 'List of Figures'
check_contains public/book/toc.html 'List of Tables'
check_contains public/book/toc.html 'Abbreviations, Acronyms and Abbreviations'
check_not_contains public/book/index.html 'site-footer-detailed'
check_not_contains public/book/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.html 'site-footer-detailed'
check_contains public/book/index.html 'upstream-atlas-favicon.png?v=2'
check_not_contains public/book/index.html 'fonts.googleapis.com'
check_not_contains public/book/index.html 'fonts.gstatic.com'
check_contains public/book/index.html 'rel="preload" href="reader-fonts/inter-var.woff2" as="font" type="font/woff2" crossorigin'
check_contains public/book/index.html 'rel="preload" href="reader-fonts/literata-var.woff2" as="font" type="font/woff2" crossorigin'
check_contains public/book/chapters/cover.html 'rel="preload" href="../reader-fonts/inter-var.woff2" as="font" type="font/woff2" crossorigin'
check_contains public/book/chapters/cover.html 'rel="preload" href="../reader-fonts/literata-var.woff2" as="font" type="font/woff2" crossorigin'
check_exists public/book/reader-fonts/inter-var.woff2
check_exists public/book/reader-fonts/literata-var.woff2
check_not_contains public/book/index.html 'favicon-de23e50b.svg'
check_not_contains public/book/index.html 'favicon-8114d1fc.png'
check_not_contains public/book/index.html 'class="book-home-label"'
check_not_contains public/book/index.html 'Upstream Atlas</span>'
check_contains theme/custom.css '@font-face {'
check_contains theme/custom.css 'font-family: "Inter";'
check_contains theme/custom.css 'url("../reader-fonts/inter-var.woff2") format("woff2");'
check_contains theme/custom.css 'font-family: "Literata";'
check_contains theme/custom.css 'url("../reader-fonts/literata-var.woff2") format("woff2");'
check_contains theme/custom.css 'font-display: block;'
check_contains theme/custom.css '--reader-sans: "Inter", -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;'
check_contains theme/custom.css '--reader-serif: "Literata", Georgia, serif;'
check_contains theme/custom.css '--menu-bar-height: 56px;'
check_contains theme/custom.css '.reader-article {'
check_contains theme/custom.css '.reader-article blockquote {'
check_contains theme/custom.css 'font-family: var(--reader-serif);'
check_contains theme/custom.css 'color: var(--ink);'
check_contains theme/custom.css '.reader-article p,'
check_contains theme/custom.css '.reader-article li {'
check_contains theme/custom.css 'color: var(--ink);'
check_contains theme/custom.css '--reader-left-offset: 0px;'
check_contains theme/custom.css '.book-toolbar {'
check_contains theme/custom.css '.toolbar-contact-link {'
check_contains theme/custom.css 'min-height: 56px;'
check_contains theme/custom.css 'padding: 0 16px;'
check_contains theme/custom.css '.book-home-icon {'
check_contains theme/custom.css '.book-home-icon-full {'
check_contains theme/custom.css 'width: 138px;'
check_contains theme/custom.css '.book-home-icon-compact {'
check_contains theme/custom.css 'width: 24px;'
check_contains theme/custom.css 'height: 24px;'
check_contains theme/custom.css '.book-cover-entry {'
check_not_contains theme/custom.css 'body.book-page-aux-index .chapter-pagination {'
check_contains theme/custom.css '@media (max-width: 900px) {'
check_not_contains theme/custom.css '.book-home-label {'
check_contains theme/custom.css '.toolbar-search-slot {'
check_contains theme/custom.css 'width: 17rem;'
check_contains theme/custom.css 'max-width: calc(100vw - 12rem);'
check_contains theme/custom.css '.toolbar-search-slot #mdbook-searchbar-outer {'
check_contains theme/custom.css '#mdbook-search-overlay-root .searchresults-outer {'
check_contains theme/custom.css '.toolbar-search-slot #mdbook-searchbar {'
check_contains theme/custom.css 'position: fixed;'
check_contains theme/custom.css 'inset-inline-start: var(--reader-left-offset);'
check_contains theme/custom.css 'inset-inline-end: var(--outline-width);'
check_contains theme/custom.css 'top: calc(var(--menu-bar-height) + 12px);'
check_contains theme/custom.css 'max-width: none;'
check_contains theme/custom.css 'max-height: calc(100dvh - var(--menu-bar-height) - 2rem);'
check_contains theme/custom.css '@media (min-width: 1281px) {'
check_contains theme/custom.css 'inset-inline-start: 50%;'
check_contains theme/custom.css 'transform: translateX(-50%);'
check_contains theme/custom.css 'width: 420px;'
check_contains theme/custom.css 'max-width: calc(100vw - 28rem);'
check_contains theme/custom.css '@media (max-width: 1280px) {'
check_contains theme/custom.css 'inset-inline-end: 0;'
check_contains theme/custom.css '#mdbook-menu-bar .book-toolbar .icon-button,'
check_contains theme/custom.css '#mdbook-menu-bar .book-toolbar .toolbar-link {'
check_contains theme/custom.css 'display: inline-flex;'
check_contains theme/custom.css 'justify-content: center;'
check_contains theme/custom.css 'width: 36px;'
check_contains theme/custom.css 'height: 36px;'
check_contains theme/custom.css 'flex: 0 0 36px;'
check_contains theme/custom.css 'line-height: 1;'
check_contains theme/custom.css '#mdbook-menu-bar .book-toolbar .fa-svg,'
check_contains theme/custom.css '#mdbook-menu-bar .book-toolbar .icon-button .fa-svg,'
check_contains theme/custom.css '#mdbook-menu-bar .book-toolbar .toolbar-link .fa-svg {'
check_contains theme/custom.css 'display: block;'
check_contains theme/custom.css 'width: 20px;'
check_contains theme/custom.css 'height: 20px;'
check_contains theme/custom.css 'pointer-events: none;'
check_contains theme/custom.css '.reader-layout {'
check_contains theme/custom.css '--outline-width: 256px;'
check_contains theme/custom.css 'grid-template-columns: minmax(0, 1fr) var(--outline-width);'
check_contains theme/custom.css '.book-sidebar-shell {'
check_contains theme/custom.css '--sidebar-width: 256px;'
check_contains theme/custom.css 'top: var(--menu-bar-height);'
check_contains theme/custom.css '@media (min-width: 1024px) {'
check_contains theme/custom.css '--sidebar-width: 288px;'
check_contains theme/custom.css '--content-max-width: 896px;'
check_contains theme/index.hbs "shim.id = 'mdbook-sidebar-resize-handle';"
check_contains theme/index.hbs "shim.style.display = 'none';"
check_contains theme/index.hbs '<button id="mdbook-theme-toggle" type="button" tabindex="-1"></button>'
check_contains theme/index.hbs '<ul id="mdbook-theme-list" class="theme-popup" aria-label="Themes" role="menu">'
check_contains theme/index.hbs '<div id="mdbook-search-overlay-root" aria-hidden="true"></div>'
check_contains theme/index.hbs '<div id="mdbook-search-wrapper" class="hidden">'
check_contains theme/index.hbs '<div class="toolbar-search-slot hidden" aria-hidden="true"></div>'
check_contains theme/index.hbs 'function applyInitialBookPageVariant()'
check_contains theme/custom.css '.book-sidebar-shell .chapter li a {'
check_contains theme/custom.css 'font-size: 14px;'
check_contains theme/custom.css '.book-sidebar-shell .chapter li.part-title {'
check_contains theme/custom.css 'font-size: 12px;'
check_contains theme/custom.css '.reader-outline {'
check_contains theme/custom.css 'overflow-y: auto;'
check_contains theme/custom.css '#mdbook-page-wrapper {'
check_contains theme/custom.css 'overflow-y: hidden;'
check_contains theme/custom.css '#mdbook-menu-bar-hover-placeholder {'
check_contains theme/custom.css 'height: 0;'
check_contains theme/custom.css '.page {'
check_contains theme/custom.css 'display: flex;'
check_contains theme/custom.css 'flex-direction: column;'
check_contains theme/custom.css 'margin-block-start: 0;'
check_contains theme/custom.css 'padding: 0;'
check_contains theme/custom.css '.content {'
check_contains theme/custom.css 'overflow: hidden;'
check_contains theme/custom.css '.reader-main {'
check_contains theme/custom.css 'overflow-y: auto;'
check_contains theme/custom.css 'padding-inline-start: calc(24px + var(--reader-left-offset));'
check_contains theme/custom.css 'padding-inline-end: 24px;'
check_contains theme/custom.css 'transition: padding-inline-start 180ms ease;'
check_contains theme/custom.css '.reader-main-inner {'
check_contains theme/custom.css 'min-height: fit-content;'
check_contains theme/custom.css 'height: auto;'
check_contains theme/custom.css 'background: #f8fafc;'
check_contains theme/custom.css 'border-inline-start: 1px solid rgba(30, 41, 59, 0.08);'
check_contains theme/custom.css '.book-progress {'
check_contains theme/custom.css 'margin-inline-start: var(--reader-left-offset);'
check_contains theme/custom.css 'width: calc(100% - var(--reader-left-offset));'
check_contains theme/custom.css 'transition: width 180ms ease, margin-inline-start 180ms ease;'
check_contains theme/custom.css '#mdbook-sidebar-toggle-anchor:checked ~ #mdbook-page-wrapper {'
check_contains theme/custom.css '--reader-left-offset: var(--sidebar-width);'
check_contains theme/custom.css 'margin-inline-start: 0;'
check_not_contains theme/custom.css 'width: min(100%, calc(100vw - var(--sidebar-width)));'
check_not_contains theme/custom.css 'margin-inline-start: var(--sidebar-width);'
check_contains theme/custom.css '.reader-article {'
check_contains theme/custom.css 'margin-inline: auto;'
check_contains theme/custom.css '.chapter-pagination {'
check_contains theme/custom.css 'margin-inline: auto;'
check_contains theme/custom.css 'max-width: var(--content-max-width);'
check_contains theme/custom.css '.book-outline-inner {'
check_contains theme/custom.css 'height: auto;'
check_contains theme/custom.css 'min-height: fit-content;'
check_contains theme/custom.css 'border: 0;'
check_contains theme/custom.css 'background: transparent;'
check_contains theme/custom.css 'box-shadow: none;'
check_contains theme/custom.css '.book-outline-label {'
check_contains theme/custom.css 'font-size: 12px;'
check_contains theme/custom.css '.on-this-page {'
check_contains theme/custom.css '.on-this-page .chapter-fold-toggle {'
check_contains theme/custom.css 'display: none;'
check_contains theme/custom.css '.on-this-page a,'
check_contains theme/custom.css '.on-this-page a:visited {'
check_contains theme/custom.css 'font-size: 14px;'
check_contains theme/custom.css 'color: #64748b;'
check_contains theme/custom.css '.content h1 {'
check_contains theme/custom.css '.content main {'
check_contains theme/custom.css 'font-size: 16px;'
check_contains theme/custom.css 'line-height: 1.625;'
check_contains theme/custom.css '.content h1 {'
check_contains theme/custom.css 'font-size: 30px;'
check_contains theme/custom.css '@media (min-width: 768px) {'
check_contains theme/custom.css 'font-size: 36px;'
check_contains theme/custom.css '.content h2 {'
check_contains theme/custom.css 'font-size: 24px;'
check_contains theme/custom.css '.content h3 {'
check_contains theme/custom.css 'font-size: 20px;'
check_contains theme/custom.css '.content p {'
check_contains theme/custom.css '.content table {'
check_contains theme/custom.css '.reader-article table,'
check_contains theme/custom.css 'font-family: var(--reader-sans);'
check_contains theme/custom.css 'font-size: 14px;'
check_contains theme/custom.css 'body.book-page-cover .reader-layout {'
check_contains theme/custom.css 'body.book-page-cover .reader-outline {'
check_contains theme/custom.css 'body.book-page-cover .chapter-pagination {'
check_contains theme/custom.css 'body.book-page-aux-index {'
check_not_contains theme/custom.css 'body.book-page-aux-index .reader-layout {'
check_contains theme/custom.css 'body.book-page-aux-index .reader-article {'
check_not_contains theme/custom.css 'max-width: 880px;'
check_contains theme/custom.css '.book-cover {'
check_contains theme/custom.css '.book-cover-frame {'
check_contains theme/custom.css '.book-cover-title {'
check_contains theme/custom.css 'padding-bottom: clamp(1.5rem, 3vw, 2.75rem);'
check_contains theme/custom.css '.book-cover-figure img {'
check_contains theme/custom.css 'aspect-ratio: 16 / 9;'
check_contains theme/custom.css '.book-cover-footer {'
check_contains theme/custom.css 'min-height: min(940px, calc(100vh - 7rem));'
check_contains theme/custom.css '@media (max-width: 760px) {'
check_contains theme/custom.css 'padding: 22px 20px 20px;'
check_contains theme/custom.css 'inset: 12px;'
check_contains theme/custom.css '.reference-index {'
check_contains theme/custom.css 'font-size: 17px;'
check_contains theme/custom.css 'padding: 14px 16px 18px;'
check_contains theme/custom.css 'font-size: 18px;'
check_contains theme/custom.css 'list-style: none;'
check_contains theme/custom.css 'padding-left: 0;'
check_contains theme/custom.css '.reference-index .reference-index-link:link,'
check_contains theme/custom.css '.reference-index .reference-index-link:visited {'
check_contains theme/custom.css 'color: var(--primary);'
check_contains theme/custom.css 'text-decoration-color: rgba(43, 91, 166, 0.18);'
check_contains theme/custom.css '.reference-index-link {'
check_contains theme/custom.css '.reference-glossary-list {'
check_not_contains theme/custom.css '.reference-index-list li::marker {'
check_contains theme/custom.css '.reference-glossary-item {'
check_contains theme/custom.css '.reader-article .api-density-formula {'
check_contains theme/custom.css '.api-density-fraction {'
check_contains theme/custom.css 'border-left: 3px solid rgba(43, 91, 166, 0.72);'
check_contains theme/custom.css 'box-shadow: 0 10px 24px rgba(15, 23, 42, 0.075);'
check_contains theme/custom.css 'font-family: var(--reader-serif);'
check_contains theme/custom.css 'padding: 13px 22px 12px;'
check_contains theme/custom.css 'font-size: clamp(18px, 1.55vw, 23px);'
check_contains theme/custom.css 'min-width: 5.8em;'
node -e 'const fs=require("fs");const css=fs.readFileSync("theme/custom.css","utf8");const block=css.match(/\.reader-article \.api-density-formula \{[^}]*\}/);if(!block||!/font-weight:\s*500;/.test(block[0])){console.error("Expected .api-density-formula to use font-weight: 500");process.exit(1);}'
node -e 'const fs=require("fs");const css=fs.readFileSync("theme/custom.css","utf8");const block=css.match(/\.api-density-numerator \{[^}]*\}/);if(!block||!/border-bottom:\s*0\.055em solid currentColor;/.test(block[0])){console.error("Expected .api-density-numerator to use border-bottom: 0.055em solid currentColor");process.exit(1);}'
check_contains theme/custom.css '.figure-card {'
check_contains theme/custom.css '.figure-card--multi .figure-media-grid {'
check_contains theme/custom.css '.figure-card--multi img {'
check_contains theme/custom.css '.figure-media {'
check_contains theme/custom.css '.figure-media-grid {'
check_contains theme/custom.css 'grid-template-columns: repeat(2, minmax(0, 1fr));'
check_contains theme/custom.css '#figure-2.figure-card--multi .figure-media-grid {'
check_contains theme/custom.css 'align-items: start;'
check_contains theme/custom.css '#figure-2.figure-card--multi .figure-media-item img {'
check_contains theme/custom.css 'height: clamp(24rem, 42vw, 46rem);'
check_contains theme/custom.css 'object-fit: contain;'
check_contains theme/custom.css 'border: 0;'
check_contains theme/custom.css 'border-radius: 0;'
check_contains theme/custom.css '#figure-7.figure-card--multi .figure-media-grid {'
check_contains theme/custom.css 'width: calc(100% - 1.75rem);'
check_contains theme/custom.css 'margin: 0 auto 0.85rem;'
check_contains theme/custom.css '#figure-7.figure-card--multi .figure-caption {'
check_contains theme/custom.css 'padding-top: 1rem;'
check_contains theme/custom.css '.figure-media-item {'
check_contains theme/custom.css '.figure-caption-label {'
check_contains theme/custom.css '.figure-caption-text {'
check_contains theme/custom.css 'display: inline-flex;'
check_contains theme/custom.css 'justify-content: center;'
check_contains theme/custom.css 'flex-wrap: wrap;'
check_contains theme/custom.css '.figure-anchor-target:target img {'
check_contains theme/custom.css '.table-anchor-target {'
check_contains theme/custom.css '.table-anchor-shell {'
check_contains theme/custom.css '.table-scroll {'
check_contains theme/custom.css '.table-anchor-target:target .table-anchor-shell {'
check_contains theme/custom.css '.table-caption {'
check_contains theme/custom.css '.table-caption-label {'
check_contains theme/custom.css '.table-caption-text {'
check_contains theme/custom.css '.table-notes {'
check_contains theme/custom.css 'font-family: var(--reader-serif);'
check_contains theme/custom.css 'font-style: italic;'
check_contains theme/custom.css 'color: rgba(30, 58, 138, 0.88);'
check_contains theme/custom.css '.table-data-table th:first-child,'
check_contains theme/custom.css '.table-data-table td:first-child {'
check_contains theme/custom.css 'text-align: left !important;'
check_contains theme/custom.css '#table-6 .table-data-table tbody td:nth-child(-n + 3) {'
check_contains theme/custom.css 'vertical-align: middle;'
check_contains theme/custom.css '#table-6 .table-data-table colgroup col:nth-child(1) {'
check_contains theme/custom.css 'width: 15% !important;'
check_contains theme/custom.css 'width: 31% !important;'
check_contains theme/custom.css 'width: 12% !important;'
check_contains theme/custom.css 'width: 42% !important;'
check_contains theme/custom.css '#table-6 .table-data-table tbody td:nth-child(4) {'
check_contains theme/custom.css 'text-align: left !important;'
check_contains theme/custom.css '#table-6 .table-data-table tbody td:nth-child(4) ul {'
check_contains theme/custom.css '.table-6-rule-list {'
check_contains theme/custom.css 'grid-template-columns: minmax(0, 1fr) auto;'
check_contains theme/custom.css '.table-6-rule-label {'
check_contains theme/custom.css '.table-6-rule-value {'
check_contains theme/custom.css 'font-variant-numeric: tabular-nums;'
check_contains theme/custom.css '#table-6 .table-data-table thead tr:first-child th {'
check_contains theme/custom.css 'font-size: 12px;'
check_contains theme/custom.css 'letter-spacing: 0.04em;'
check_contains theme/custom.css '#table-6 .table-data-table thead tr:last-child th {'
check_contains theme/custom.css 'font-size: 13px;'
check_contains theme/custom.css 'font-style: italic;'
check_contains theme/custom.css 'background: rgba(239, 246, 255, 0.8);'
check_contains theme/custom.css '#table-6 .table-data-table tbody tr:nth-child(even) td {'
check_contains theme/custom.css 'background: rgba(238, 243, 251, 0.22);'
check_contains theme/custom.css '#table-6 .table-data-table th + th,'
check_contains theme/custom.css 'border-left-color: rgba(148, 163, 184, 0.08);'
check_contains theme/custom.css 'display: table;'
check_contains theme/custom.css '.book-sidebar-shell .chapter li a {'
check_contains theme/custom.css 'padding: 8px 12px;'
check_contains theme/custom.css 'border-radius: 8px;'
check_contains theme/custom.css '.on-this-page ol,'
check_contains theme/custom.css '.on-this-page > ol,'
check_contains theme/custom.css 'padding: 0;'
check_contains theme/custom.css 'border-left: 0;'
check_contains theme/custom.css 'font-size: 14px;'
check_contains theme/custom.css 'line-height: 20px;'
check_not_contains theme/custom.css '@import url("https://fonts.googleapis.com'
check_contains theme/custom.js 'document.body.classList.add("book-outline-ready")'
check_contains theme/custom.js 'function installHeaderSearchSlot()'
check_contains theme/custom.js 'document.querySelector(".toolbar-search-slot")'
check_contains theme/custom.js 'const searchresultsOuter = document.getElementById("mdbook-searchresults-outer");'
check_contains theme/custom.js 'const searchOverlayRoot = document.getElementById("mdbook-search-overlay-root");'
check_contains theme/custom.js 'searchOverlayRoot.appendChild(searchresultsOuter);'
check_contains theme/custom.js 'function hideSearchResultsOverlay()'
check_contains theme/custom.js 'searchbar.addEventListener("input", function () {'
check_contains theme/custom.js 'if (searchbar.value.trim() === "") {'
check_contains theme/custom.js 'searchbar.addEventListener("keydown", function (event) {'
check_contains theme/custom.js 'if (event.key === "Escape") {'
check_contains theme/custom.js 'event.stopPropagation();'
check_contains theme/custom.js 'const searchToggle = document.getElementById("mdbook-search-toggle");'
check_contains theme/custom.js 'searchWrap.classList.add("hidden");'
check_contains theme/custom.js 'searchToggle.setAttribute("aria-expanded", "false");'
check_contains theme/custom.js 'searchToggle.focus();'
check_contains theme/custom.js 'toolbarSearchSlot.classList.toggle("hidden", hidden)'
check_contains theme/custom.js 'requestAnimationFrame(function focusToolbarSearchbar()'
check_contains theme/custom.js 'searchbar.focus();'
check_contains theme/custom.js 'searchbar.select();'
check_contains theme/custom.js 'function applyPageVariants()'
check_contains theme/custom.js 'cover.html'
check_not_contains theme/custom.js 'front-matter.html'
check_contains theme/custom.js 'list-of-figures.html'
check_contains theme/custom.js 'abbreviations-acronyms-and-abbreviations.html'
check_contains theme/custom.js 'document.body.classList.add("book-page-cover")'
check_contains theme/custom.js 'function annotateFigureCaptions()'
check_contains theme/custom.js 'const wrapper = document.createElement("figure")'
check_contains theme/custom.js 'wrapper.className = "figure-card figure-anchor-target"'
check_contains theme/custom.js 'wrapper.classList.add("figure-card--multi")'
check_contains theme/custom.js 'mediaBlock.classList.add("figure-media")'
check_contains theme/custom.js 'mediaCandidates.length > 1'
check_contains theme/custom.js 'mediaGrid.className = "figure-media figure-media-grid"'
check_contains theme/custom.js 'mediaItem.className = "figure-media-item"'
check_contains theme/custom.js 'captionLabel.textContent = "Figure "'
check_contains theme/custom.js '+ ":"'
check_contains theme/custom.js 'captionLabel.className = "figure-caption-label"'
check_contains theme/custom.js 'captionText.className = "figure-caption-text"'
check_contains theme/custom.js 'function annotateTables()'
check_contains theme/custom.js 'const tableId = "table-" +'
check_contains theme/custom.js 'wrapper.className = "table-anchor-target"'
check_contains theme/custom.js 'const tableShell = document.createElement("div")'
check_contains theme/custom.js 'tableShell.className = "table-anchor-shell"'
check_contains theme/custom.js 'const tableScroll = document.createElement("div")'
check_contains theme/custom.js 'tableScroll.className = "table-scroll"'
check_contains theme/custom.js 'const captionLabel = document.createElement("span")'
check_contains theme/custom.js 'captionLabel.className = "table-caption-label"'
check_contains theme/custom.js 'captionText.className = "table-caption-text"'
check_contains theme/custom.js 'caption.className = "table-caption"'
check_contains theme/custom.js 'function collectTableNotes('
check_contains theme/custom.js 'function enhanceTable6()'
check_contains theme/custom.js 'function parseTable6Rule(text)'
check_contains theme/custom.js 'ruleList.className = "table-6-rule-list"'
check_contains theme/custom.js 'ruleItem.className = "table-6-rule-item"'
check_contains theme/custom.js 'label.className = "table-6-rule-label"'
check_contains theme/custom.js 'value.className = "table-6-rule-value"'
check_contains theme/custom.js 'function buildOutlineList('
check_contains theme/custom.js 'querySelectorAll(".on-this-page a.header-in-summary")'
check_contains theme/custom.js 'document.getElementById("mdbook-reader-scroll")'
check_contains theme/custom.js 'chapters/foreword.html'
check_contains theme/custom.js 'window.location.replace(target.href)'
check_not_contains public/book/index.html 'class="book-shell-grid"'
check_not_contains public/book/index.html 'class="book-page-surface"'
check_not_contains public/book/index.html 'class="book-main-column"'
check_not_contains public/book/index.html 'reader-sidebar'
check_not_contains public/book/index.html 'book-outline-shell'
check_not_contains public/book/index.html 'toolbar-center'
check_not_contains public/book/index.html 'book-toolbar-actions'

echo "Site render checks passed."
