#!/usr/bin/env sh
set -eu

ROOT_DIR="$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)"

cd "$ROOT_DIR"
npm run build:site >/dev/null

check_contains() {
  file_path="$1"
  pattern="$2"

  if ! grep -q -- "$pattern" "$file_path"; then
    echo "Missing expected pattern '$pattern' in $file_path" >&2
    exit 1
  fi
}

check_not_contains() {
  file_path="$1"
  pattern="$2"

  if grep -q -- "$pattern" "$file_path"; then
    echo "Unexpected pattern '$pattern' found in $file_path" >&2
    exit 1
  fi
}

check_exists() {
  file_path="$1"

  if [ ! -f "$file_path" ]; then
    echo "Missing expected file $file_path" >&2
    exit 1
  fi
}

check_file_size_at_most() {
  file_path="$1"
  max_bytes="$2"
  size_bytes="$(wc -c < "$file_path" | tr -d ' ')"

  if [ "$size_bytes" -gt "$max_bytes" ]; then
    echo "Expected $file_path to be <= $max_bytes bytes but was $size_bytes bytes" >&2
    exit 1
  fi
}

check_exists scripts/generate-index-page.mjs
check_exists scripts/shared/landing-shell.mjs
check_exists assets/images/west-africa-intelligence-overlay.svg
check_contains package.json '"build:index": "node scripts/generate-index-page.mjs"'
check_contains package.json '"build:site": "rm -rf public && mkdir -p public && npm run build:index && npm run build:chapters'
check_contains scripts/generate-index-page.mjs 'renderLandingHead'
check_contains scripts/generate-index-page.mjs 'renderLandingHeader'
check_contains scripts/generate-index-page.mjs 'renderLandingFooter'
check_contains scripts/generate-chapters-page.mjs 'from "./shared/landing-shell.mjs"'
check_contains scripts/generate-chapters-page.mjs 'renderLandingHead'
check_contains scripts/generate-chapters-page.mjs 'renderLandingHeader'
check_contains scripts/generate-chapters-page.mjs 'renderLandingFooter'
check_contains scripts/shared/landing-shell.mjs 'function renderLandingHead'
check_contains scripts/shared/landing-shell.mjs 'function renderLandingHeader'
check_contains scripts/shared/landing-shell.mjs 'function renderLandingFooter'

check_contains public/index.html 'class="landing-shell"'
check_contains public/index.html 'class="hero-panel"'
check_contains public/index.html 'class="chapter-preview-card"'
check_contains public/index.html 'class="site-header-inner"'
check_contains public/index.html 'upstream-atlas-favicon.png?v=2'
check_contains public/index.html 'href="chapters/"'
check_contains public/index.html 'class="current-link" href="/">Home</a>'
check_contains public/index.html 'href="#countries">Countries</a>'
check_contains public/index.html 'href="#resources">Resources</a>'
check_contains public/index.html 'class="header-contact-link"'
check_contains public/index.html 'mailto:matt@operatorassetexchange.com?subject=Upstream%20Atlas'
check_contains public/index.html 'aria-label="Contact Us"'
check_not_contains public/index.html 'class="nav-search"'
check_not_contains public/index.html 'href="book/toc.html"'
check_not_contains public/index.html 'section-heading section-heading-centered'
check_contains public/index.html 'West African Petroleum Intelligence'
check_contains public/index.html 'West African upstream intelligence built on a rigorous reference base.'
check_contains public/index.html 'rigorous upstream reference base'
check_contains public/index.html 'Reference book'
check_contains public/index.html 'Available now'
check_contains public/index.html 'In build'
check_contains public/index.html 'Platform Intelligence'
check_contains public/index.html 'Coming Soon'
check_contains public/index.html 'class="reference-evidence-grid"'
check_contains public/index.html 'Country reserves'
check_contains public/index.html 'Country Intelligence'
check_contains public/index.html 'class="country-card country-card-compact"'
check_contains public/index.html 'Additional markets'
check_contains public/index.html 'class="country-card-top"'
check_contains public/index.html 'class="country-card-badge"'
check_contains public/index.html 'class="country-signal-grid"'
check_contains public/index.html 'class="country-signal-value"'
check_contains public/index.html 'Template ready'
check_contains public/index.html 'Brief queued'
check_contains public/index.html 'Signals planned'
check_contains public/index.html 'class="chapters-link-row"'
check_contains public/index.html 'class="footer-brand-lockup"'
check_contains public/index.html 'class="footer-brand-upstream"'
check_contains public/index.html 'class="footer-brand-atlas"'
check_not_contains public/index.html 'class="footer-brand-wordmark"'
check_contains public/index.html 'fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap'
check_file_size_at_most public/assets/images/upstream-atlas-icon.png 50000
check_file_size_at_most public/assets/images/upstream-atlas-wordmark.png 110000
check_file_size_at_most public/assets/images/prototype-hero.jpg 120000
check_contains assets/css/landing.css '--page-bg: #f7f8f9;'
check_contains assets/css/landing.css '--surface-muted: #eef2f4;'
check_contains assets/css/landing.css '--ink-primary: #0b1f33;'
check_contains assets/css/landing.css '--brand-blue: #3163c2;'
check_contains assets/css/landing.css '--brand-blue-deep: #264d97;'
check_contains assets/css/landing.css '--footer-bg: #0b1f33;'
check_contains assets/css/landing.css '--secondary: #d88a1d;'
check_contains assets/css/landing.css '--text: var(--ink-primary);'
check_contains assets/css/landing.css 'opacity: 0.28;'
check_contains assets/css/landing.css 'background: linear-gradient(135deg, rgba(38, 77, 151, 0.82) 0%, rgba(11, 31, 51, 0.84) 100%);'
check_contains assets/css/landing.css 'background: var(--brand-blue-deep);'
check_contains assets/css/landing.css 'background: url("../images/prototype-hero.jpg") center right / cover;'
check_contains assets/css/landing.css 'background: url("../images/west-africa-intelligence-overlay.svg") center / cover no-repeat;'
check_contains assets/css/landing.css 'opacity: 0.09;'
check_not_contains assets/css/landing.css '--primary: #264d97;'
check_contains assets/css/landing.css '@media (min-width: 901px) {'
check_contains assets/css/landing.css '.hero-signal-panel {'
check_contains assets/css/landing.css 'margin-top: clamp(17rem, 30vw, 20.5rem);'
check_contains assets/css/landing.css '.chapters-link-row {'
check_contains assets/css/landing.css 'width: min(76rem, calc(100% - 2rem));'
check_contains assets/css/landing.css '.chapters-link {'
check_contains assets/css/landing.css 'margin: 0;'
check_contains assets/css/landing.css 'border-radius: 0.5rem;'
check_contains assets/css/landing.css 'font-weight: 500;'
check_contains assets/css/landing.css 'font-family: "Manrope", "Inter", sans-serif;'
check_contains assets/css/landing.css '.mobile-nav-toggle {'
check_contains assets/css/landing.css '.header-actions {'
check_contains assets/css/landing.css '.header-contact-link::after {'
check_contains assets/css/landing.css '.mobile-nav-contact {'
check_contains assets/css/landing.css '@media (max-width: 700px) {'
check_contains assets/css/landing.css '.site-header-inner {'
check_contains assets/css/landing.css 'grid-template-columns: auto auto;'
check_not_contains assets/css/landing.css '@import url("https://fonts.googleapis.com'
check_not_contains scripts/generate-chapters-page.mjs 'replaceAll('
check_not_contains assets/css/chapters.css 'var(--primary)'
check_not_contains assets/css/chapters.css '--primary:'
check_contains assets/css/chapters.css 'var(--ink-primary)'
check_contains assets/css/chapters.css 'var(--brand-blue)'

check_exists public/chapters/index.html
check_contains public/chapters/index.html 'Chapter Library'
check_contains public/chapters/index.html 'class="site-header-inner"'
check_contains public/chapters/index.html 'class="button button-header" href="../book/">Start Reading</a>'
check_contains public/chapters/index.html 'class="current-link" href="./">Chapters</a>'
check_contains public/chapters/index.html 'href="../#countries">Countries</a>'
check_contains public/chapters/index.html 'href="../#resources">Resources</a>'
check_contains public/chapters/index.html 'href="../#about">About</a>'
check_contains public/chapters/index.html 'class="header-contact-link"'
check_contains public/chapters/index.html 'mailto:matt@operatorassetexchange.com?subject=Upstream%20Atlas'
check_contains public/chapters/index.html 'class="footer-brand-lockup"'
check_contains public/chapters/index.html 'class="footer-brand-upstream"'
check_contains public/chapters/index.html 'class="footer-brand-atlas"'
check_contains public/chapters/index.html 'fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&family=Manrope:wght@500;600;700;800&display=swap'
check_not_contains public/chapters/index.html 'class="nav-search"'
check_not_contains public/chapters/index.html 'href="../#audience"'
check_not_contains public/chapters/index.html 'class="footer-brand-wordmark"'
check_contains public/chapters/index.html '<h2>Part I: General Information on the Oil Industry</h2>'
check_contains public/chapters/index.html 'class="chapter-card-header"'
check_contains public/chapters/index.html 'class="chapter-card-status"'
check_contains public/chapters/index.html 'class="chapter-card-reading"'
check_contains public/chapters/index.html 'data-tooltip="Estimated reading time based on'
check_contains public/chapters/index.html 'Estimated reading time based on'
check_contains public/chapters/index.html 'Additional Resources'
check_not_contains public/chapters/index.html 'Open chapter'
check_not_contains public/chapters/index.html ' entries</p>'
check_not_contains public/chapters/index.html 'title="Estimated reading time based on'
check_contains public/chapters/index.html 'General Information on the Oil Industry'
check_contains public/chapters/index.html '../book/chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.html'

check_contains public/book/index.html 'id="mdbook-sidebar"'
check_contains public/book/index.html 'class="light sidebar-visible"'
check_contains public/book/index.html 'id="book-progress-fill"'
check_contains public/book/index.html 'class="book-toolbar"'
check_contains public/book/index.html 'class="toolbar-left"'
check_contains public/book/index.html 'class="toolbar-right"'
check_contains public/book/index.html 'class="icon-button toolbar-link toolbar-contact-link"'
check_contains public/book/index.html 'href="mailto:matt@operatorassetexchange.com?subject=Upstream%20Atlas"'
check_contains public/book/index.html 'title="Contact Us"'
check_contains public/book/index.html 'class="toolbar-search-slot hidden"'
check_contains public/book/index.html 'id="mdbook-search-wrapper" class="hidden"'
check_contains public/book/index.html 'id="mdbook-content" class="content reader-layout"'
check_contains public/book/index.html 'reader-layout'
check_contains public/book/index.html 'reader-main'
check_contains public/book/index.html 'reader-outline'
check_contains public/book/index.html 'id="mdbook-reader-scroll"'
check_contains public/book/index.html 'id="mdbook-outline-scroll"'
check_contains public/book/index.html 'class="reader-main-inner"'
check_contains public/book/index.html 'reader-article'
check_contains public/book/index.html 'book-sidebar-shell'
check_not_contains public/book/index.html 'sidebar-resize-indicator'
check_not_contains public/book/index.html 'class="sidebar-resize-handle"'
check_not_contains public/book/index.html 'title="Print this book"'
check_not_contains public/book/index.html 'title="Suggest an edit"'
check_not_contains public/book/index.html 'title="Change theme"'
check_contains public/book/index.html 'class="book-outline-inner"'
check_contains public/book/index.html 'class="chapter-nav-card chapter-nav-next"'
check_not_contains public/book/toc.html 'href="index.html" target="_parent">Home</a>'
check_contains public/book/chapters/chapter-04-comparative-study-of-tax-regimes-in-selected-west-african-countries.html 'reader-layout'
check_contains public/book/chapters/chapter-04-comparative-study-of-tax-regimes-in-selected-west-african-countries.html 'reader-main'
check_contains public/book/chapters/chapter-04-comparative-study-of-tax-regimes-in-selected-west-african-countries.html 'reader-outline'
check_contains public/book/chapters/chapter-04-comparative-study-of-tax-regimes-in-selected-west-african-countries.html 'reader-article'
check_contains public/book/index.html 'upstream-atlas-favicon.png?v=2'
check_contains public/book/index.html 'fonts.googleapis.com/css2?family=Inter:wght@400;500;600&family=Lora:wght@400;500;600;700&display=swap'
check_not_contains public/book/index.html 'favicon-de23e50b.svg'
check_not_contains public/book/index.html 'favicon-8114d1fc.png'
check_contains theme/custom.css '--menu-bar-height: 56px;'
check_contains theme/custom.css '.reader-article {'
check_contains theme/custom.css 'color: var(--ink);'
check_contains theme/custom.css '.reader-article p,'
check_contains theme/custom.css '.reader-article li {'
check_contains theme/custom.css 'color: var(--ink);'
check_contains theme/custom.css '--reader-left-offset: 0px;'
check_contains theme/custom.css '.book-toolbar {'
check_contains theme/custom.css '.toolbar-contact-link {'
check_contains theme/custom.css 'min-height: 56px;'
check_contains theme/custom.css 'padding: 0 16px;'
check_contains theme/custom.css '.book-home-icon {'
check_contains theme/custom.css 'width: 24px;'
check_contains theme/custom.css 'height: 24px;'
check_contains theme/custom.css '.book-home-label {'
check_contains theme/custom.css 'font-size: 14px;'
check_contains theme/custom.css '.toolbar-search-slot {'
check_contains theme/custom.css 'width: 17rem;'
check_contains theme/custom.css 'max-width: calc(100vw - 12rem);'
check_contains theme/custom.css '.toolbar-search-slot #mdbook-searchbar-outer {'
check_contains theme/custom.css '#mdbook-search-overlay-root .searchresults-outer {'
check_contains theme/custom.css '.toolbar-search-slot #mdbook-searchbar {'
check_contains theme/custom.css 'position: fixed;'
check_contains theme/custom.css 'inset-inline-start: var(--reader-left-offset);'
check_contains theme/custom.css 'inset-inline-end: var(--outline-width);'
check_contains theme/custom.css 'top: calc(var(--menu-bar-height) + 12px);'
check_contains theme/custom.css 'max-width: none;'
check_contains theme/custom.css 'max-height: calc(100dvh - var(--menu-bar-height) - 2rem);'
check_contains theme/custom.css '@media (min-width: 1281px) {'
check_contains theme/custom.css 'inset-inline-start: 50%;'
check_contains theme/custom.css 'transform: translateX(-50%);'
check_contains theme/custom.css 'width: 420px;'
check_contains theme/custom.css 'max-width: calc(100vw - 28rem);'
check_contains theme/custom.css '@media (max-width: 1280px) {'
check_contains theme/custom.css 'inset-inline-end: 0;'
check_contains theme/custom.css '#mdbook-menu-bar .book-toolbar .icon-button,'
check_contains theme/custom.css '#mdbook-menu-bar .book-toolbar .toolbar-link {'
check_contains theme/custom.css 'display: inline-flex;'
check_contains theme/custom.css 'justify-content: center;'
check_contains theme/custom.css 'width: 36px;'
check_contains theme/custom.css 'height: 36px;'
check_contains theme/custom.css 'flex: 0 0 36px;'
check_contains theme/custom.css 'line-height: 1;'
check_contains theme/custom.css '#mdbook-menu-bar .book-toolbar .fa-svg,'
check_contains theme/custom.css '#mdbook-menu-bar .book-toolbar .icon-button .fa-svg,'
check_contains theme/custom.css '#mdbook-menu-bar .book-toolbar .toolbar-link .fa-svg {'
check_contains theme/custom.css 'display: block;'
check_contains theme/custom.css 'width: 20px;'
check_contains theme/custom.css 'height: 20px;'
check_contains theme/custom.css 'pointer-events: none;'
check_contains theme/custom.css '.reader-layout {'
check_contains theme/custom.css '--outline-width: 256px;'
check_contains theme/custom.css 'grid-template-columns: minmax(0, 1fr) var(--outline-width);'
check_contains theme/custom.css '.book-sidebar-shell {'
check_contains theme/custom.css '--sidebar-width: 256px;'
check_contains theme/custom.css 'top: var(--menu-bar-height);'
check_contains theme/custom.css '@media (min-width: 1024px) {'
check_contains theme/custom.css '--sidebar-width: 288px;'
check_contains theme/custom.css '--content-max-width: 896px;'
check_contains theme/index.hbs "shim.id = 'mdbook-sidebar-resize-handle';"
check_contains theme/index.hbs "shim.style.display = 'none';"
check_contains theme/index.hbs '<button id="mdbook-theme-toggle" type="button" tabindex="-1"></button>'
check_contains theme/index.hbs '<ul id="mdbook-theme-list" class="theme-popup" aria-label="Themes" role="menu">'
check_contains theme/index.hbs '<div id="mdbook-search-overlay-root" aria-hidden="true"></div>'
check_contains theme/index.hbs '<div id="mdbook-search-wrapper" class="hidden">'
check_contains theme/index.hbs '<div class="toolbar-search-slot hidden" aria-hidden="true"></div>'
check_contains theme/custom.css '.book-sidebar-shell .chapter li a {'
check_contains theme/custom.css 'font-size: 14px;'
check_contains theme/custom.css '.book-sidebar-shell .chapter li.part-title {'
check_contains theme/custom.css 'font-size: 12px;'
check_contains theme/custom.css '.reader-outline {'
check_contains theme/custom.css 'overflow-y: auto;'
check_contains theme/custom.css '#mdbook-page-wrapper {'
check_contains theme/custom.css 'overflow-y: hidden;'
check_contains theme/custom.css '#mdbook-menu-bar-hover-placeholder {'
check_contains theme/custom.css 'height: 0;'
check_contains theme/custom.css '.page {'
check_contains theme/custom.css 'display: flex;'
check_contains theme/custom.css 'flex-direction: column;'
check_contains theme/custom.css 'margin-block-start: 0;'
check_contains theme/custom.css 'padding: 0;'
check_contains theme/custom.css '.content {'
check_contains theme/custom.css 'overflow: hidden;'
check_contains theme/custom.css '.reader-main {'
check_contains theme/custom.css 'overflow-y: auto;'
check_contains theme/custom.css 'padding-inline-start: calc(24px + var(--reader-left-offset));'
check_contains theme/custom.css 'padding-inline-end: 24px;'
check_contains theme/custom.css 'transition: padding-inline-start 180ms ease;'
check_contains theme/custom.css '.reader-main-inner {'
check_contains theme/custom.css 'min-height: fit-content;'
check_contains theme/custom.css 'height: auto;'
check_contains theme/custom.css 'background: #f8fafc;'
check_contains theme/custom.css 'border-inline-start: 1px solid rgba(30, 41, 59, 0.08);'
check_contains theme/custom.css '.book-progress {'
check_contains theme/custom.css 'margin-inline-start: var(--reader-left-offset);'
check_contains theme/custom.css 'width: calc(100% - var(--reader-left-offset));'
check_contains theme/custom.css 'transition: width 180ms ease, margin-inline-start 180ms ease;'
check_contains theme/custom.css '#mdbook-sidebar-toggle-anchor:checked ~ #mdbook-page-wrapper {'
check_contains theme/custom.css '--reader-left-offset: var(--sidebar-width);'
check_contains theme/custom.css 'margin-inline-start: 0;'
check_not_contains theme/custom.css 'width: min(100%, calc(100vw - var(--sidebar-width)));'
check_not_contains theme/custom.css 'margin-inline-start: var(--sidebar-width);'
check_contains theme/custom.css '.reader-article {'
check_contains theme/custom.css 'margin-inline: auto;'
check_contains theme/custom.css '.chapter-pagination {'
check_contains theme/custom.css 'margin-inline: auto;'
check_contains theme/custom.css 'max-width: var(--content-max-width);'
check_contains theme/custom.css '.book-outline-inner {'
check_contains theme/custom.css 'height: auto;'
check_contains theme/custom.css 'min-height: fit-content;'
check_contains theme/custom.css 'border: 0;'
check_contains theme/custom.css 'background: transparent;'
check_contains theme/custom.css 'box-shadow: none;'
check_contains theme/custom.css '.book-outline-label {'
check_contains theme/custom.css 'font-size: 12px;'
check_contains theme/custom.css '.on-this-page {'
check_contains theme/custom.css '.on-this-page .chapter-fold-toggle {'
check_contains theme/custom.css 'display: none;'
check_contains theme/custom.css '.on-this-page a,'
check_contains theme/custom.css '.on-this-page a:visited {'
check_contains theme/custom.css 'font-size: 14px;'
check_contains theme/custom.css 'color: #64748b;'
check_contains theme/custom.css '.content h1 {'
check_contains theme/custom.css '.content main {'
check_contains theme/custom.css 'font-size: 16px;'
check_contains theme/custom.css 'line-height: 1.625;'
check_contains theme/custom.css '.content h1 {'
check_contains theme/custom.css 'font-size: 30px;'
check_contains theme/custom.css '@media (min-width: 768px) {'
check_contains theme/custom.css 'font-size: 36px;'
check_contains theme/custom.css '.content h2 {'
check_contains theme/custom.css 'font-size: 24px;'
check_contains theme/custom.css '.content h3 {'
check_contains theme/custom.css 'font-size: 20px;'
check_contains theme/custom.css '.content p {'
check_contains theme/custom.css '.content table {'
check_contains theme/custom.css 'font-size: 14px;'
check_contains theme/custom.css '.book-sidebar-shell .chapter li a {'
check_contains theme/custom.css 'padding: 0.5rem 0.75rem;'
check_contains theme/custom.css '.on-this-page ol,'
check_contains theme/custom.css '.on-this-page > ol,'
check_contains theme/custom.css 'padding: 0;'
check_contains theme/custom.css 'border-left: 0;'
check_contains theme/custom.css 'font-size: 14px;'
check_not_contains theme/custom.css '@import url("https://fonts.googleapis.com'
check_contains theme/custom.js 'document.body.classList.add("book-outline-ready")'
check_contains theme/custom.js 'function installHeaderSearchSlot()'
check_contains theme/custom.js 'document.querySelector(".toolbar-search-slot")'
check_contains theme/custom.js 'const searchresultsOuter = document.getElementById("mdbook-searchresults-outer");'
check_contains theme/custom.js 'const searchOverlayRoot = document.getElementById("mdbook-search-overlay-root");'
check_contains theme/custom.js 'searchOverlayRoot.appendChild(searchresultsOuter);'
check_contains theme/custom.js 'function hideSearchResultsOverlay()'
check_contains theme/custom.js 'searchbar.addEventListener("input", function () {'
check_contains theme/custom.js 'if (searchbar.value.trim() === "") {'
check_contains theme/custom.js 'searchbar.addEventListener("keydown", function (event) {'
check_contains theme/custom.js 'if (event.key === "Escape") {'
check_contains theme/custom.js 'event.stopPropagation();'
check_contains theme/custom.js 'const searchToggle = document.getElementById("mdbook-search-toggle");'
check_contains theme/custom.js 'searchWrap.classList.add("hidden");'
check_contains theme/custom.js 'searchToggle.setAttribute("aria-expanded", "false");'
check_contains theme/custom.js 'searchToggle.focus();'
check_contains theme/custom.js 'toolbarSearchSlot.classList.toggle("hidden", hidden)'
check_contains theme/custom.js 'requestAnimationFrame(function focusToolbarSearchbar()'
check_contains theme/custom.js 'searchbar.focus();'
check_contains theme/custom.js 'searchbar.select();'
check_contains theme/custom.js 'function normalizeOutline('
check_contains theme/custom.js 'querySelectorAll("a.header-in-summary")'
check_contains theme/custom.js 'document.getElementById("mdbook-reader-scroll")'
check_contains theme/custom.js 'chapters/chapter-01-value-chain-of-the-hydrocarbon-sector.html'
check_contains theme/custom.js 'window.location.replace(target.href)'
check_not_contains public/book/index.html 'class="book-shell-grid"'
check_not_contains public/book/index.html 'class="book-page-surface"'
check_not_contains public/book/index.html 'class="book-main-column"'
check_not_contains public/book/index.html 'reader-sidebar'
check_not_contains public/book/index.html 'book-outline-shell'
check_not_contains public/book/index.html 'toolbar-center'
check_not_contains public/book/index.html 'book-toolbar-actions'

echo "Site render checks passed."
