[book]
title = "Exploration et exploitation des ressources pétrolières en Afrique de l’Ouest"
authors = ["Edison"]
language = "fr"
src = "src"

[output.html]
theme = "theme"
default-theme = "light"
preferred-dark-theme = "navy"
additional-css = ["theme/custom.css"]
additional-js = ["theme/ga.js", "theme/custom.js"]
site-url = "/fr/book/"
no-section-label = true
